# Generated by Django 4.2.2 on 2025-02-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_remove_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="default_user", max_length=50),
        ),
    ]
