# Generated by Django 5.1.5 on 2025-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="publication_attribute",
            new_name="is_publication",
        ),
        migrations.AlterField(
            model_name="blog",
            name="number_of_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Колличество просмотров"
            ),
        ),
    ]
